spring:
  r2dbc:
    pool:
      enabled: true
      initial-size: 2
      validation-query: SELECT 1
      max-size: 100
    url: r2dbc:mysql://localhost:3306/test
#    url: r2dbc:mariadb://localhost:3306/test?socketTimeout=3s
    password: root
    username: root
    queryTimeout: 3

logging:
  level:
    org.springframework.r2dbc: TRACE
    io.r2dbc.pool: TRACE
    com.github.jasync: TRACE
    org.springframework.transaction.interceptor: TRACE
    reactor.pool: TRACE
    org.springframework.transaction.reactive: TRACE
    org.mariadb.r2dbc: TRACE

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - prometheus